apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nginx
spec:
  scaleTargetRef:
    apiVersion: apps/vi
    kind: Deployment
    name: nginx-deploy
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 1
