apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: nginx-deploy
  minReplicas: 1			
  maxReplicas: 3			
  targetCPUUtilizationPercentage: 1
