apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeployment
  labels:
    app: mysqlapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysqlapp
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysqlapp
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root123!
